language: node_js
node_js:
  - "8"
warnings_are_errors: false
before_install:
  - npm install -g firebase-tools
install:
  - npm install
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - firebase use dev
      - firebase functions:config:set tmdb.key=${TMDB_API_KEY}
      - firebase deploy --non-interactive --project dev --token ${FIREBASE_TOKEN}
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script:
      - firebase use prod
      - firebase functions:config:set tmdb.key=${TMDB_API_KEY}
      - firebase deploy --non-interactive --project prod --token ${FIREBASE_TOKEN}
    on:
      branch: master
