language: node_js
node_js:
  - "8"
warnings_are_errors: false
before_install:
  - npm install -g firebase-tools
install:
  - npm install
deploy:
  - provider: firebase
    project: dev
    skip_cleanup: true
    token:
      secure: mac49ToKyfXhaRfNKD3kh8b3lV5aRFxMgRfkLRp7OLsVFl88VJKmsQ9j4amXh74DVbE1DUtZMYxuLhrM1hAmRNicNcKl0yEceBlDWPNSZHIcDjuLZRqLvikJgXKR1qsUDqbDIi3mIfgVPEReVWX4AxzmZ6LJd2T/ZfVpld3ohGjTQMo2PskbpwCoeiBx8i8caGME46aNAJb6KqnzbCItEfQTo3H9RyrbOLjbnVlKdv15DDkId9DOtUF8QN+i0EYcYTVARgxkYrQ0Ob6JW8Hop4Ok+ytQfWU3lqGwWWvZFUN9Tmiubdp3+goYcsPXOQxlx/ADySWSeIIzWshpHYxa/UjX3N6RSFNykB4ZZEA2KycDK0WLivPklZoIhIXsagpariB5dRdZY9t0+W28rUSj3eikwQlnjEET/oIWZp4FgGkkOby+W4rOtiqgaAV4Zm+uG94nzbTQ0mvQEvZJ5Ief4OnmYy7PW2I/j9nYCvmzX225P//iKszcgW4UKqvVtj9hV5y/lvLfrGTPk0os8iDfVEOUqL9TCQgfWtHqyK3y86/q4U7T0K0zaiTVuT3JWmRGiMAdmxPvFdEKRsuM+0hPCfTmZ63WMBoU6L1TWHVnOuZnd/S9rB1JaSF7+9fkyUJxdgjs4YypSxwguoxj0GUycUXB/nAOIHq7xGhCe1H0iqg=
    on:
      branch: develop
  - provider: firebase
    project: prod
    skip_cleanup: true
    token:
      secure: ZU0qoLfc9I9aC/GoVYnkhZwVd0exfarTi7fyh+04HrOv2UNXLGRLJEsLOtL3LnUX+KkcS2VdSJPe894IosqqkVG93j8zk3w0cGH4Nc1JA1vMJyQ1elptPp1LkPjBHkqc73fBuWs5vexvrpAtLT5k0vcLNGWrchDTU1Fa/jcnkLgitUnrUcsllvtK+n0yZW9+0ypXX0Vy1yehOHbJps6TBvZivp4FCd18smI354xuFkFaKyALM8OWokxySevaA+igKGgOGI/y2l9Po2MXuPsEQF41gpiMFGWPAgjJMn11EYsdYfeUQZiMaFmkyB9ysmyt558Mf796AZuQojjtArUS9yn5LrWxDq1lLolFGStUYVxAllq3iEeTGZbt4wWWGafP+hARrcj/Ygg7F0v5ndMC4iPgKHTUcquZL+TYCDjAvcM67zCn01h276Wn+aCfu5bAkRKtmfga6IpLwf15ulmYoSJp5rKoal7O9xSQRxwfIoj1LjJHxvjAzKB/sYjK/yxpkW9wYb1Y6iZvXG8B0290vptEA7gJ4d9JpWNAJuKLyn7e0Nudl8USV1TQE8OW/MyUNd34MQC8G82t8nJKUbo/fPACG4zjoXIc195M0BMkgiNFNZKzxuoC4kqNBdDDgATGkuowdn3JNRpy0SBHX0oh4GARJKsKZ77mn/VAGXd+1B4=
    on:
      branch: master
